[theme]

# Primary accent for interactive elements
primaryColor = '#00BFFF'

# Background color for the main content area
backgroundColor = '#00008B'  # Dark blue

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#A9A9A9'  # White

# Color used for almost all text
textColor = '#FFFFFF'  # White or any other color that is visible on dark blue

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
